version: "3"

services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      # - ./php-magento2-module:/var/www/html/app/code/Kaypay/Payment:ro

  phpfpm:
    volumes: *appvolumes

  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"
    volumes:
      - appdata:/var/www/html:rw
